[package]
name = "fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[[bin]]
bench = false
doc = false
name = "fuzz_convert"
path = "fuzz_targets/fuzz_convert.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_scale"
path = "fuzz_targets/fuzz_scale.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_rotate"
path = "fuzz_targets/fuzz_rotate.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_planar"
path = "fuzz_targets/fuzz_planar.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_compare"
path = "fuzz_targets/fuzz_compare.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_mjpeg"
path = "fuzz_targets/fuzz_mjpeg.rs"
test = false

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"

[dependencies.shiguredo_libyuv]
path = ".."
